server:
  port: 8888
spring:
  application:
    name: config-server
  rabbitmq: # rabbitmq 접속
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/soodal5629/spring-cloud-config.git # 뒤에 .git 생략 가능!!

management: # actuator endpoint 설정
  endpoints:
    web:
      exposure:
        include: health, busrefresh
